### ISSUE TITLE
Errors with pytest

### ISSUE THREAD

**Issue by LucasColas** [SirRender00/texasholdem#207] opened 2023-07-08 05:15 UTC
Hello,
I ran `test_game.py` (with pytest).
However I came across several errors : 
ERROR test_game.py::test_new_game
ERROR test_game.py::test_basic_prehand
ERROR test_game.py::test_skip_prehand
ERROR test_game.py::test_heads_up_edge_case
ERROR test_game.py::test_blind_all_in_prehand
ERROR test_game.py::test_game_stop_prehand
ERROR test_game.py::test_basic_betting_rounds[HandPhase.PREFLOP-1-0]
ERROR test_game.py::test_basic_betting_rounds[HandPhase.FLOP-2-3]
ERROR test_game.py::test_basic_betting_rounds[HandPhase.TURN-3-4]
ERROR test_game.py::test_basic_betting_rounds[HandPhase.RIVER-4-5]
ERROR test_game.py::test_basic_settle
ERROR test_game.py::test_basic_continuity
ERROR test_game.py::test_until_stop[predicates0]

I used the code of the actual main branch. 
Do you know if it's normal ?
Bye.

**Comment by SirRender00** [comment] 2023-07-17 05:49
Hmm, I cannot reproduce this. Can you double check if everything is up to date (git pull, poetry install, etc.) and then run 

```bash
poetry run pytest -s
```

**Comment by SirRender00** [comment] 2023-07-20 17:55
Closing this for now, please respond if you are still have troubles with this

**Closed by SirRender00** 2023-07-20 17:55 UTC
Labels: question
